### ISSUE TITLE
Decoding the binary 

### ISSUE THREAD

**Issue by P4sca1** [criblio/js2bin#8]
I am wondering whether it is possible to decode the binary and read the compressed, base64 encoded source code?

Basically is my code secure from being copied when handing out the binary?

**Comment by ledbit** [comment]
@P4sca1 - yes it is possible to decode the binary, but not straightforward. Your code would be a bit more secure than handing out the `.js` file. My recommendation would be to uglify, minify then embed into the binary - if there are sensitive parts of your code you can obfuscate them [even more] (https://obfuscator.io/) before embedding. 

I've also filed #9 which should help in providing better obfuscation as a V8 snapshot would be embedded instead of the `.js` file itself

**Comment by P4sca1** [comment]
Alright, thank you for the info and thanks for making this open source! :)
